use super::index::{project_name, resolve_session_file};
use super::types::{ContentBlock, Message, SessionDetail, TokenUsage};
use serde::Deserialize;
use serde_json::Value;
use std::collections::HashSet;
use std::io::{BufRead, BufReader};
use std::path::Path;

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct RawEntry {
    #[serde(rename = "type")]
    entry_type: Option<String>,
    message: Option<RawMessage>,
    timestamp: Option<Value>,
    /// `{"type":"ai-title","aiTitle":"…"}` — generated by Claude Code.
    #[serde(rename = "aiTitle")]
    ai_title: Option<String>,
    /// `{"type":"custom-title","customTitle":"…"}` — user rename in /resume.
    #[serde(rename = "customTitle")]
    custom_title: Option<String>,
}

#[derive(Deserialize)]
struct RawMessage {
    id: Option<String>,
    content: Option<Value>,
    model: Option<String>,
    usage: Option<RawUsage>,
}

#[derive(Deserialize, Default)]
struct RawUsage {
    input_tokens: Option<u64>,
    output_tokens: Option<u64>,
    cache_read_input_tokens: Option<u64>,
    cache_creation_input_tokens: Option<u64>,
}

pub fn get_session(
    home: &Path,
    session_id: &str,
    project: &str,
    timestamp: u64,
) -> Option<SessionDetail> {
    let session_file = resolve_session_file(home, project, session_id)?;
    let file = std::fs::File::open(&session_file).ok()?;
    let reader = BufReader::new(file);

    let mut messages: Vec<Message> = Vec::new();
    let mut seen_ids: HashSet<String> = HashSet::new();
    let mut total_usage = TokenUsage::default();
    let mut overall_model: Option<String> = None;
    let mut title: Option<String> = None;
    let mut custom_title: Option<String> = None;
    let mut first_ts: Option<u64> = None;
    let mut last_ts: Option<u64> = None;
    let mut error_count: u32 = 0;

    for line in reader.lines() {
        let line = match line {
            Ok(l) => l,
            Err(_) => break,
        };
        let line = line.trim();
        if line.is_empty() {
            continue;
        }

        let entry: RawEntry = match serde_json::from_str(line) {
            Ok(e) => e,
            Err(_) => continue,
        };

        match entry.entry_type.as_deref() {
            Some("permission-mode") | Some("file-history-snapshot") | None => continue,
            // Titles: a user rename always beats the generated title; within a
            // kind, the last record in the file wins.
            Some("ai-title") => {
                if custom_title.is_none() {
                    if let Some(t) = entry.ai_title.filter(|t| !t.trim().is_empty()) {
                        title = Some(t);
                    }
                }
                continue;
            }
            Some("custom-title") => {
                if let Some(t) = entry.custom_title.filter(|t| !t.trim().is_empty()) {
                    title = Some(t.clone());
                    custom_title = Some(t);
                }
                continue;
            }
            Some("user") => {
                let msg = match &entry.message {
                    Some(m) => m,
                    None => continue,
                };
                let ts = parse_timestamp(&entry.timestamp);
                if let Some(t) = ts {
                    first_ts.get_or_insert(t);
                    last_ts = Some(t);
                }
                let content = parse_content_blocks(msg.content.as_ref(), &mut error_count);
                messages.push(Message {
                    role: "user".to_string(),
                    content,
                    timestamp: ts,
                    model: None,
                    usage: None,
                });
            }
            Some("assistant") => {
                let msg = match &entry.message {
                    Some(m) => m,
                    None => continue,
                };

                // Dedup streaming entries by message.id
                if let Some(msg_id) = &msg.id {
                    if !seen_ids.insert(msg_id.clone()) {
                        continue;
                    }
                }

                let ts = parse_timestamp(&entry.timestamp);
                if let Some(t) = ts {
                    first_ts.get_or_insert(t);
                    last_ts = Some(t);
                }

                let model = msg.model.as_deref().map(shorten_model_name);
                if overall_model.is_none() {
                    overall_model = model.clone();
                }

                let usage = msg.usage.as_ref().map(|u| {
                    let tok = TokenUsage {
                        input_tokens: u.input_tokens.unwrap_or(0),
                        output_tokens: u.output_tokens.unwrap_or(0),
                        cache_read_tokens: u.cache_read_input_tokens.unwrap_or(0),
                        cache_creation_tokens: u.cache_creation_input_tokens.unwrap_or(0),
                    };
                    total_usage.input_tokens += tok.input_tokens;
                    total_usage.output_tokens += tok.output_tokens;
                    total_usage.cache_read_tokens += tok.cache_read_tokens;
                    total_usage.cache_creation_tokens += tok.cache_creation_tokens;
                    tok
                });

                let content = parse_content_blocks(msg.content.as_ref(), &mut error_count);
                messages.push(Message {
                    role: "assistant".to_string(),
                    content,
                    timestamp: ts,
                    model,
                    usage,
                });
            }
            _ => {}
        }
    }

    let duration_ms = match (first_ts, last_ts) {
        (Some(f), Some(l)) if l > f => Some(l - f),
        _ => None,
    };

    Some(SessionDetail {
        agent: "claude".to_string(),
        session_id: session_id.to_string(),
        messages,
        title,
        total_tokens: total_usage,
        model: overall_model,
        duration_ms,
        project: project.to_string(),
        project_name: project_name(project),
        timestamp,
    })
}

fn parse_timestamp(ts: &Option<Value>) -> Option<u64> {
    match ts {
        Some(Value::Number(n)) => n.as_u64().or_else(|| n.as_f64().map(|f| f as u64)),
        Some(Value::String(s)) => s.parse::<u64>().ok(),
        _ => None,
    }
}

fn shorten_model_name(model: &str) -> String {
    let stripped = model.trim_start_matches("claude-");
    let parts: Vec<&str> = stripped.split('-').collect();
    // Strip trailing 8-digit date suffix
    if let Some(last) = parts.last() {
        if last.len() == 8 && last.chars().all(|c| c.is_ascii_digit()) {
            return parts[..parts.len() - 1].join("-");
        }
    }
    stripped.to_string()
}

fn parse_content_blocks(content: Option<&Value>, error_count: &mut u32) -> Vec<ContentBlock> {
    let mut blocks = Vec::new();
    match content {
        Some(Value::String(s)) => {
            let sanitized = sanitize_xml(s);
            if !sanitized.trim().is_empty() {
                blocks.push(ContentBlock {
                    block_type: "text".to_string(),
                    text: Some(sanitized),
                    tool_name: None,
                    tool_input: None,
                    tool_result: None,
                    is_error: false,
                    tool_use_id: None,
                });
            }
        }
        Some(Value::Array(arr)) => {
            for item in arr {
                if let Some(block) = parse_single_block(item, error_count) {
                    blocks.push(block);
                }
            }
        }
        _ => {}
    }
    blocks
}

fn parse_single_block(item: &Value, error_count: &mut u32) -> Option<ContentBlock> {
    let block_type = item.get("type")?.as_str()?.to_string();
    match block_type.as_str() {
        "text" => {
            let text = item.get("text")?.as_str()?;
            let sanitized = sanitize_xml(text);
            if sanitized.trim().is_empty() {
                return None;
            }
            Some(ContentBlock {
                block_type: "text".to_string(),
                text: Some(sanitized),
                tool_name: None,
                tool_input: None,
                tool_result: None,
                is_error: false,
                tool_use_id: None,
            })
        }
        "tool_use" => {
            let name = item.get("name")?.as_str()?.to_string();
            let input = item.get("input").map(|v| truncate_str(&v.to_string(), 500));
            Some(ContentBlock {
                block_type: "tool_use".to_string(),
                text: None,
                tool_name: Some(name),
                tool_input: input,
                tool_result: None,
                is_error: false,
                tool_use_id: item
                    .get("id")
                    .and_then(|v| v.as_str())
                    .map(str::to_string),
            })
        }
        "tool_result" => {
            let is_error = item
                .get("is_error")
                .and_then(|v| v.as_bool())
                .unwrap_or(false);
            if is_error {
                *error_count += 1;
            }
            // Emit the block so the frontend can pair it with its tool_use by
            // id and show the output. Blocks with no id / no content are still
            // worth keeping when they mark an error.
            let tool_use_id = item
                .get("tool_use_id")
                .and_then(|v| v.as_str())
                .map(str::to_string);
            let tool_result = extract_result_text(item.get("content"));
            if tool_use_id.is_none() && tool_result.is_none() && !is_error {
                return None;
            }
            Some(ContentBlock {
                block_type: "tool_result".to_string(),
                text: None,
                tool_name: None,
                tool_input: None,
                tool_result,
                is_error,
                tool_use_id,
            })
        }
        // Skip thinking blocks — internal model cognition, not user-facing content
        _ => None,
    }
}

/// A `tool_result` block's `content` is either a bare string or an array of
/// `{type:"text", text:"…"}` parts (image parts are ignored). Returns the
/// joined, sanitized, length-capped text, or None when there's nothing useful.
fn extract_result_text(content: Option<&Value>) -> Option<String> {
    let raw = match content {
        Some(Value::String(s)) => s.clone(),
        Some(Value::Array(arr)) => arr
            .iter()
            .filter_map(|part| {
                if part.get("type").and_then(|v| v.as_str()) == Some("text") {
                    part.get("text").and_then(|v| v.as_str())
                } else {
                    None
                }
            })
            .collect::<Vec<_>>()
            .join("\n"),
        _ => return None,
    };
    let cleaned = sanitize_xml(&raw);
    let cleaned = cleaned.trim();
    if cleaned.is_empty() {
        return None;
    }
    Some(truncate_str(cleaned, 2000))
}

fn truncate_str(s: &str, max: usize) -> String {
    if s.len() <= max {
        s.to_string()
    } else {
        // Truncate at char boundary
        let end = s
            .char_indices()
            .map(|(i, _)| i)
            .take_while(|&i| i <= max)
            .last()
            .unwrap_or(max);
        format!("{}…", &s[..end])
    }
}

fn sanitize_xml(s: &str) -> String {
    let s = strip_tagged_content(s, "system-reminder");
    strip_tagged_content(&s, "command-name")
}

fn strip_tagged_content(s: &str, tag: &str) -> String {
    let open = format!("<{tag}>");
    let close = format!("</{tag}>");
    let mut result = String::with_capacity(s.len());
    let mut rest = s;
    loop {
        match rest.find(&*open) {
            None => {
                result.push_str(rest);
                break;
            }
            Some(start) => {
                result.push_str(&rest[..start]);
                rest = &rest[start + open.len()..];
                if let Some(end) = rest.find(&*close) {
                    rest = &rest[end + close.len()..];
                } else {
                    break;
                }
            }
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn tool_use_block_captures_its_id() {
        let mut errs = 0;
        let block = parse_single_block(
            &json!({"type": "tool_use", "id": "toolu_abc", "name": "Bash", "input": {"command": "ls"}}),
            &mut errs,
        )
        .unwrap();
        assert_eq!(block.block_type, "tool_use");
        assert_eq!(block.tool_use_id.as_deref(), Some("toolu_abc"));
        assert_eq!(errs, 0);
    }

    #[test]
    fn tool_result_string_content_is_surfaced_and_paired() {
        let mut errs = 0;
        let block = parse_single_block(
            &json!({"type": "tool_result", "tool_use_id": "toolu_abc", "content": "3 files"}),
            &mut errs,
        )
        .unwrap();
        assert_eq!(block.block_type, "tool_result");
        assert_eq!(block.tool_use_id.as_deref(), Some("toolu_abc"));
        assert_eq!(block.tool_result.as_deref(), Some("3 files"));
        assert!(!block.is_error);
        assert_eq!(errs, 0);
    }

    #[test]
    fn tool_result_array_content_is_joined() {
        let mut errs = 0;
        let block = parse_single_block(
            &json!({"type": "tool_result", "tool_use_id": "t1", "content": [
                {"type": "text", "text": "line one"},
                {"type": "image", "source": {}},
                {"type": "text", "text": "line two"}
            ]}),
            &mut errs,
        )
        .unwrap();
        assert_eq!(block.tool_result.as_deref(), Some("line one\nline two"));
    }

    #[test]
    fn tool_result_error_increments_count_and_keeps_block() {
        let mut errs = 0;
        let block = parse_single_block(
            &json!({"type": "tool_result", "tool_use_id": "t1", "is_error": true, "content": "boom"}),
            &mut errs,
        )
        .unwrap();
        assert!(block.is_error);
        assert_eq!(block.tool_result.as_deref(), Some("boom"));
        assert_eq!(errs, 1);
    }

    #[test]
    fn empty_non_error_tool_result_is_dropped() {
        let mut errs = 0;
        assert!(parse_single_block(
            &json!({"type": "tool_result", "content": ""}),
            &mut errs,
        )
        .is_none());
        assert_eq!(errs, 0);
    }

    #[test]
    fn result_text_strips_system_reminder_noise() {
        let got = extract_result_text(Some(&json!(
            "real output<system-reminder>ignored</system-reminder>"
        )));
        assert_eq!(got.as_deref(), Some("real output"));
    }
}
